resolver: lts-3.14
compiler: ghcjs-0.2.0.20151029_ghc-7.10.2
compiler-check: match-exact
setup-info:
  ghcjs:
    source:
      ghcjs-0.2.0.20151029_ghc-7.10.2:
        url: "https://github.com/nrolland/ghcjs/releases/download/v0.2.0.20151029/ghcjs-0.2.0.20151029.tar.gz"

packages:
- '.'

- location:
    git: git@github.com:ghcjs/ghcjs-jquery.git
    commit: d81a1fee88923194971ed4e8a52736a639080d74

extra-deps:
  - ghcjs-dom-0.2.3.0

flags: {}
extra-package-dbs: []